apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mongo:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 27017
        imagePullPolicy: Always