apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    nodePort: 30000 # 30000 - 302222
    targetPort: 80
    protocol: TCP

    # 3 types of svc - Cluster-IP - NodePort - LoadBalancer